language: ruby
bundler_args: --without development production

addons:
  postgresql: 9.4

env:
  - RAILS_ENV=test PG_HOST=localhost PG_USERNAME=postgres

before_script:
  - bundle exec rake db:create db:migrate

notifications:
  slack: wcmc:1edFn9otArYeHhPizMrEZGfK
